import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import YAML from "yaml";
import { parsePack } from "@runlog/rules-schema";
import { runFixtures } from "../packages/cli/src/fixtures.ts";

/**
 * The reference is generated, but a generated file still has to be regenerated.
 *
 * The failure this guards is specific and quiet: someone adds a field, ships
 * it, and the reference silently keeps describing the format as it was. A
 * document that is merely out of date would be tolerable; one that is out of
 * date in the place people go to check is worse than none.
 *
 * Rather than re-running the generator here — which would mean a second copy
 * of its logic, the exact trap the schema staleness test fell into — this
 * asserts the cheap, load-bearing property: every field the schema accepts is
 * named somewhere in the reference.
 */

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const schema = JSON.parse(
  readFileSync(join(repoRoot, "packages", "rules-schema", "schema", "pack-1.schema.json"), "utf8"),
) as Record<string, unknown>;
const reference = readFileSync(join(repoRoot, "docs", "reference.md"), "utf8");

/** Every property name the format accepts, anywhere in the schema. */
function everyFieldName(node: unknown, into = new Set<string>()): Set<string> {
  if (typeof node !== "object" || node === null) return into;
  if (Array.isArray(node)) {
    for (const item of node) everyFieldName(item, into);
    return into;
  }
  for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
    if (key === "properties" && typeof value === "object" && value !== null) {
      for (const name of Object.keys(value)) into.add(name);
    }
    everyFieldName(value, into);
  }
  return into;
}

describe("the generated pack reference", () => {
  it("is marked as generated, so nobody edits it by hand", () => {
    expect(reference).toContain("Generated by packages/rules-schema/scripts/emit-reference.ts");
    expect(reference).toContain("Do not edit");
  });

  it("points authors at the schema URL their editor needs", () => {
    expect(reference).toContain("yaml-language-server: $schema=");
  });

  it("names every field the format accepts", () => {
    const fields = [...everyFieldName(schema)].sort();
    expect(fields.length).toBeGreaterThan(60);

    const missing = fields.filter((name) => !reference.includes(`\`${name}\``));
    if (missing.length > 0) {
      throw new Error(
        `${missing.length} field(s) are in the schema but not in docs/reference.md:\n` +
          `  ${missing.join(", ")}\n\n` +
          `Run \`npm run docs:emit\` and commit the result.`,
      );
    }
    expect(missing).toEqual([]);
  });

  it("links to the guide a person actually wrote", () => {
    // The reference says what the fields are; it cannot say why you would want
    // any of them, and a reference alone teaches nobody the format.
    expect(reference).toContain("authoring.md");
  });
});

describe("the authoring guide", () => {
  const guide = readFileSync(join(repoRoot, "docs", "authoring.md"), "utf8");

  /**
   * A guide whose example does not load is worse than no example: it teaches
   * the format wrongly and costs the reader an hour finding out. So the pack
   * printed in the guide is pulled out of the prose and put through the same
   * gates a contributor's pack goes through.
   */
  describe("the complete pack it prints", () => {
    // Tolerant of CRLF: this file gets edited on Windows too.
    const fenced = new RegExp("```yaml\\r?\\n([\\s\\S]*?)```", "g");
    const blocks = [...guide.matchAll(fenced)].map((m) => m[1]!);
    const complete = blocks.filter(
      (b) => b.includes("schemaVersion: 1") && b.includes("defaultMode:"),
    );

    it("is there, exactly once", () => {
      expect(complete).toHaveLength(1);
    });

    it("loads, and cleanly enough for --strict", () => {
      const result = parsePack(YAML.parse(complete[0]!));
      const shown = result.diagnostics.map((d) => `${d.code} at ${d.path}: ${d.message}`);
      expect(shown).toEqual([]);
      expect(result.ok).toBe(true);
    });

    it("passes the fixtures it ships", () => {
      // The guide tells authors to run `runlog test`. Its own example had
      // better survive it.
      const result = parsePack(YAML.parse(complete[0]!));
      if (!result.ok || !result.pack) throw new Error("the guide's pack did not load");
      const results = runFixtures(result.pack);
      expect(results.length).toBeGreaterThan(0);
      for (const r of results) expect(r, r.name).toMatchObject({ ok: true });
    });
  });

  it("covers the commands an author needs", () => {
    for (const command of ["runlog validate", "runlog test", "runlog bundle", "runlog init"]) {
      expect(guide).toContain(command);
    }
  });

  it("is honest about the license field", () => {
    // Someone transcribing a book they bought needs to know this exists, and
    // needs to know what the app does about it.
    expect(guide).toContain("redistributable");
  });
});
