import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { loadPackText, loadSetupText, type Pack, type Setup } from "@runlog/rules-schema";
// A type and nothing else: it is erased, so the engine does not follow this
// package into a browser. What it buys is the pin below, where the layout
// the page publishes has to still be the layout a profile is laid out from.
import type { LiveSnapshot } from "@runlog/engine";

import { PACK_PROFILES } from "../../../streamdeck/src/profiles.ts";
import { BASE, DEVICES, DEVICE_IDS, FRAMES, POOLS, UTILITY, UTILITY_PAGE, type Frame, type Key } from "./layouts.ts";
import {
  GENERIC,
  container,
  framedPages,
  fromOffer,
  fromPack,
  hasKeys,
  packKeys,
  paginate,
  profile,
  shippedName,
  specs,
  specsFor,
  type Built,
  type Keyed,
  type Laid,
  type PageFile,
  type Queues,
  type RootFile,
  type StoredAction,
} from "./profiles.ts";

/**
 * The generator, held against the packs it reads and the grids its output
 * has to fit on.
 *
 * Nobody reads a `.streamDeckProfile`. It is a zip of compact JSON that
 * goes out with a release or off a pack's page and turns up on somebody's
 * desk, and the two ways it goes wrong, a key off the edge of a Mini and a
 * move whose id the pack renamed last month, both look to whoever imported
 * it like the plugin being broken. So the layout is held to the grid and to
 * the pack here, where a mistake costs a test run rather than a support
 * thread.
 *
 * The last and largest check is that this package rebuilds the forty-four
 * files committed under the plugin, byte for byte. Those are generated by
 * `streamdeck/design/profiles.mjs`, which is a Node script over this code;
 * proving the package alone reproduces them is what says a browser
 * building a profile for a Marketplace pack is building the same thing.
 */

const repo = new URL("../../../", import.meta.url);
const path = (rest: string) => fileURLToPath(new URL(rest, repo));

/** Every setup written for a tool, by title, the way the app's picker lists them. */
function setupsFor(tool: string | undefined): Setup[] {
  if (!tool) return [];
  const dir = path("packs/setups");
  const out: Setup[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".yaml"))) {
    const parsed = loadSetupText(readFileSync(`${dir}/${file}`, "utf8"), "yaml");
    if (parsed.ok && parsed.setup.tool.toLowerCase() === tool.toLowerCase()) out.push(parsed.setup);
  }
  return out.sort((a, b) => a.title.localeCompare(b.title));
}

/** The tool a pack is driven by, from the control profile written for it. */
function toolFor(packId: string): string | undefined {
  const dir = path("packs/profiles");
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const written = JSON.parse(readFileSync(`${dir}/${file}`, "utf8")) as { pack?: string; tool?: string };
    if (written.pack === packId) return written.tool;
  }
  return undefined;
}

/**
 * The layouts the plugin ships, read the way the generator reads them.
 *
 * The slug each pack ships under comes from `streamdeck/src/profiles.ts`,
 * the table the generator writes and the plugin switches through, rather
 * than from a second copy of the naming rule kept here.
 */
const shipped: Array<{ slug: string; pack: Pack | null; setups: Setup[] }> = [{ slug: "runlog", pack: null, setups: [] }];
for (const file of ["packs/demo/pack.yaml", ...readdirSync(path("packs/sketches")).map((f) => `packs/sketches/${f}`)]) {
  if (!file.endsWith(".yaml")) continue;
  const parsed = loadPackText(readFileSync(path(file), "utf8"), "yaml");
  if (!parsed.ok) continue;
  const slug = PACK_PROFILES[parsed.pack.id];
  if (slug) shipped.push({ slug, pack: parsed.pack, setups: setupsFor(toolFor(parsed.pack.id)) });
}

/**
 * Every layout on every deck, built, with the slug and the name it ships under.
 *
 * The slug is the generator's: the file each pack is kept in, which the
 * script puts on each spec. The name comes out of `specs` already marked,
 * so nothing here spells it.
 */
const all = shipped.flatMap(({ slug, pack, setups }) =>
  specs(pack, setups).map((spec) => {
    const named = { ...spec, slug };
    return { spec: named, built: profile(named) };
  }),
);

/** Every action on every page of a built profile, with the page and position it sits at. */
function placed(built: Built): Array<{ page: string; controller: string; position: string; action: StoredAction }> {
  const out = [];
  for (const [page, file] of Object.entries(built.files)) {
    if (!("Controllers" in file)) continue;
    for (const controller of file.Controllers) {
      for (const [position, action] of Object.entries(controller.Actions ?? {})) {
        out.push({ page, controller: controller.Type, position, action });
      }
    }
  }
  return out;
}

/** Each page's keys, in page order. The empty default page carries none and is left out. */
function pages(built: Built): Array<Record<string, StoredAction>> {
  const out: Array<Record<string, StoredAction>> = [];
  for (const file of Object.values(built.files)) {
    if (!("Controllers" in file)) continue;
    const keypad = file.Controllers.find((c) => c.Type === "Keypad");
    if (keypad?.Actions) out.push(keypad.Actions);
  }
  return out;
}

/**
 * What sits in one cell, short enough to write a grid out in a test.
 *
 * The action's own last word, with whatever the key is set to after it, and
 * `turn:` for the app's own page keys, whose last word is `next` as well.
 */
function at(page: Record<string, StoredAction>, cell: string): string {
  const action = page[cell];
  if (!action) return "";
  const name = action.UUID.split(".").pop()!;
  if (action.UUID.startsWith("com.elgato.")) return `turn:${name}`;
  const settings = action.Settings;
  if (name === "metric") {
    const field = settings["field"];
    return `metric:${typeof field === "string" ? field : Object.values(field as Record<string, string>)[0]}`;
  }
  if (name === "open") return `open:${String(settings["target"])}`;
  if (name === "press") return `press:${(settings["target"] as { id: string }).id}`;
  return name;
}

/** Every cell of a deck's grid but the ones named, for holding a page to what is on it. */
function others(device: "xl" | "sd" | "mini" | "plus", taken: string[]): string[] {
  const { columns, rows } = DEVICES[device];
  const out: string[] = [];
  for (let row = 0; row < rows; row++) {
    for (let column = 0; column < columns; column++) {
      const cell = `${column},${row}`;
      if (!taken.includes(cell)) out.push(cell);
    }
  }
  return out;
}

/** A page as its rows, so a whole grid can be held in one expectation. */
function grid(page: Record<string, StoredAction>, device: "xl" | "sd"): string[][] {
  const { columns, rows } = DEVICES[device];
  return Array.from({ length: rows }, (_, row) => Array.from({ length: columns }, (_, column) => at(page, `${column},${row}`)));
}

/** The last page of a profile, as the cells it puts a key or the way back in. */
function corner(device: "xl" | "sd"): string[] {
  return [...UTILITY_PAGE[device].map((u) => u.at), FRAMES[device]!.turns.previous];
}

/** A frame small enough to write out, for the paging and the spill rules. */
const pooled = (over: Partial<Frame>): Frame => ({
  fixed: [],
  extras: { numbers: { first: [], last: [] }, setups: { first: [], last: [] }, moves: { first: [], last: [] } },
  pools: { numbers: [], setups: [], moves: [] },
  spill: { numbers: ["setups", "moves"], setups: ["numbers", "moves"], moves: ["setups", "numbers"] },
  turns: { next: "0,0", previous: "0,0" },
  utility: [],
  ...over,
});

/** A pack with more moves than a page holds and two numbers, for the paging rules. */
const crowded: Keyed = {
  moves: Array.from({ length: 20 }, (_, i) => ({ id: `move${i}` })),
  counters: [{ id: "one" }, { id: "two" }],
  resources: [],
  setups: [],
  commands: [],
};

/** A pack big enough to overrun all three pools on an XL, for the spill order. */
const synthetic: Keyed = {
  moves: Array.from({ length: 12 }, (_, i) => ({ id: `move${i}` })),
  counters: Array.from({ length: 12 }, (_, i) => ({ id: `count${i}` })),
  resources: [],
  // Titled so the sort by title leaves them in the order they are written.
  setups: Array.from({ length: 9 }, (_, i) => ({ id: `setup${i}`, title: `Setup ${i}` })),
  commands: [],
};

/** One layout, built for one deck, as its pages. */
const deck = (keyed: Keyed | null, device: "xl" | "sd" | "mini" | "plus") =>
  pages(profile(specsFor(keyed, { slug: "test", name: "Test" }, device)[0]!));

describe("a deck laid out for a pack", () => {
  it("knows how big each deck is", () => {
    // Written out rather than taken from `DEVICES`, which is the table
    // under test: the grid check below reads the same numbers the layout
    // was built from, so without this it would pass on any pair of them.
    // These are the SDK's, from the `DeviceType` enumeration in
    // @elgato/schemas.
    expect(DEVICES.xl).toMatchObject({ type: 2, columns: 8, rows: 4, dials: 0 });
    expect(DEVICES.sd).toMatchObject({ type: 0, columns: 5, rows: 3, dials: 0 });
    expect(DEVICES.mini).toMatchObject({ type: 1, columns: 3, rows: 2, dials: 0 });
    expect(DEVICES.plus).toMatchObject({ type: 7, columns: 4, rows: 2, dials: 4 });
    expect(DEVICE_IDS).toEqual(Object.keys(DEVICES));
  });

  it("keeps a page's last slot for the way on, and its first for the way back", () => {
    const keys = Array.from({ length: 20 }, (_, i) => ({ action: `k${i}` }));
    // Six to a page: five on the first with the sixth spent going on, then
    // four with both turns, then the rest with only the way back.
    expect(paginate(keys, 6).map((p) => [p.back, p.more, p.keys.length])).toEqual([
      [false, true, 5],
      [true, true, 4],
      [true, true, 4],
      [true, true, 4],
      [true, false, 3],
    ]);
    // A layout that fits exactly grows no turn key pointing at nothing.
    expect(paginate(keys.slice(0, 6), 6)).toEqual([{ back: false, more: false, keys: keys.slice(0, 6) }]);
    // With a page to follow, which on every profile is the utility page,
    // the last page pays for the way on like any other.
    expect(paginate(keys.slice(0, 6), 6, true)).toEqual([
      { back: false, more: true, keys: keys.slice(0, 5) },
      { back: true, more: true, keys: keys.slice(5, 6) },
    ]);
  });

  it("spills a queue into another pool's cells once that pool's own queue has run dry", () => {
    // Two by three, one key pinned, a cell for each of the three pools, and
    // the turns along the bottom.
    const frame = pooled({
      fixed: [{ key: { action: "connect" }, at: "0,0" }],
      pools: { numbers: ["1,0"], setups: ["0,1"], moves: ["1,1"] },
      turns: { next: "1,2", previous: "0,2" },
      utility: [{ key: UTILITY[0]!, at: "1,2" }],
    });
    const key = (action: string) => ({ action });
    const empty = { numbers: [], setups: [], moves: [] };
    // Every profile ends on the utility page, which is tested on its own
    // below; what the queues did is the pages ahead of it.
    const queued = (over: Partial<Queues>) => framedPages(frame, { ...empty, ...over }).slice(0, -1);

    // Nothing queued is still one page of its own: the frame is the profile.
    expect(queued({})).toEqual([{ back: false, more: true, keys: { "0,0": key("connect") } }]);

    // Numbers alone: its own cell first, then the setups pool, then the moves.
    expect(queued({ numbers: [key("n"), key("o"), key("p")] })).toEqual([
      { back: false, more: true, keys: { "0,0": key("connect"), "1,0": key("n"), "0,1": key("o"), "1,1": key("p") } },
    ]);

    // Moves alone: its own cell first, then the setups pool, then the numbers.
    expect(queued({ moves: [key("a"), key("b"), key("c")] })).toEqual([
      { back: false, more: true, keys: { "0,0": key("connect"), "1,1": key("a"), "0,1": key("b"), "1,0": key("c") } },
    ]);

    // The moves spill before the setups do, so the one free cell goes to a
    // move and the setup left over pages.
    const both = queued({ moves: [key("a"), key("b")], setups: [key("s"), key("t")] });
    expect(both[0]!.keys).toEqual({ "0,0": key("connect"), "1,1": key("a"), "0,1": key("s"), "1,0": key("b") });
    expect(both[1]!.keys["0,1"]).toEqual(key("t"));
  });

  it("spends the way on even where the queues would have fitted without it", () => {
    // Every page ahead of the utility page pays for a way on to it, so a
    // frame filled to the brim pages one key earlier than the cells alone
    // say. No frame the plugin ships is in that position: all forty-four
    // profiles cut the same pages they did before the utility page, plus
    // it. A frame changed until one is trips this, which is the point.
    const frame = pooled({
      pools: { numbers: [], setups: [], moves: ["0,0", "0,1", "0,2"] },
      turns: { next: "0,2", previous: "0,0" },
      utility: [
        { key: UTILITY[0]!, at: "0,1" },
        { key: UTILITY[1]!, at: "0,2" },
      ],
    });
    const key = (action: string) => ({ action });
    const pages = framedPages(frame, { numbers: [], setups: [], moves: [key("a"), key("b"), key("c")] });
    // Three cells and three keys, and two pages of the keys, then the
    // utility page, which is its own cells and nothing else.
    expect(pages.map((p) => [p.back, p.more, Object.keys(p.keys)])).toEqual([
      [false, true, ["0,0", "0,1"]],
      [true, true, ["0,1"]],
      [true, false, ["0,1", "0,2"]],
    ]);
    expect(pages[1]!.keys["0,1"]).toEqual(key("c"));
    expect(pages[2]!.keys["0,1"]).toEqual(UTILITY[0]);
  });

  it("ends on the keys that are not about the run, whatever the queues did", () => {
    const frame = pooled({
      fixed: [{ key: { action: "connect" }, at: "0,0" }],
      pools: { numbers: ["1,1"], setups: [], moves: ["0,1"] },
      turns: { next: "1,2", previous: "0,2" },
      utility: [
        { key: UTILITY[0]!, at: "1,1" },
        { key: UTILITY[1]!, at: "1,2" },
      ],
    });
    // Every queue empty and the utility page is still cut: its own cells,
    // none of the frame, and no way on from the last page of a profile.
    const pages = framedPages(frame, { numbers: [], setups: [], moves: [] });
    expect(pages).toHaveLength(2);
    expect(pages[1]).toEqual({ back: true, more: false, keys: { "1,1": UTILITY[0], "1,2": UTILITY[1] } });
  });

  it("stops on a frame with nowhere to put a key rather than paging for ever", { timeout: 2000 }, () => {
    // No free cell in any pool, which no deck here has, but this is
    // exported: without the guard the queue would never come down and the
    // page count would never stop climbing.
    const walled = pooled({
      fixed: [{ key: { action: "connect" }, at: "0,0" }],
      turns: { next: "0,1", previous: "1,1" },
    });
    // One page of the frame, then the utility page, which this frame gives
    // no cell to put a utility key in either.
    expect(framedPages(walled, { numbers: [], setups: [], moves: [{ action: "press" }] })).toEqual([
      { back: false, more: true, keys: { "0,0": { action: "connect" } } },
      { back: true, more: false, keys: {} },
    ]);
  });

  it("lays an XL out the way the streamer laid one out", () => {
    const [page, ...rest] = deck(null, "xl");
    // The run down the left, nothing of a pack's to put anywhere else, and
    // the way on to the utility page in the bottom right corner.
    expect(grid(page!, "xl")).toEqual([
      ["connect", "run", "undo", "clock", "", "", "", ""],
      ["next", "metric:latest", "metric:unit", "metric:score", "", "", "", ""],
      ["roll", "", "", "", "", "", "", ""],
      ["finish", "", "", "", "", "", "", "turn:next"],
    ]);
    // Two pages: this one and the utility page.
    expect(rest).toHaveLength(1);
  });

  it("ends an XL on the keys that are not about the run, and nothing else", () => {
    const [, second, ...rest] = deck(null, "xl");
    expect(rest).toHaveLength(0);
    // The last page is not the run's, so it does not wear the run's frame:
    // Connect and the run where they always are, and everything that is
    // not about the run in hand in the right two columns.
    expect(grid(second!, "xl")).toEqual([
      ["connect", "run", "", "", "", "", "open:rules", "open:guide"],
      ["", "", "", "", "", "", "open:run", "open:newrun"],
      ["", "", "", "", "", "", "autoroll", "open:dock"],
      ["", "", "", "", "", "", "turn:previous", "install"],
    ]);
    for (const cell of others("xl", corner("xl"))) expect(at(second!, cell), cell).toBe("");
  });

  it("gives an XL the pack's counters top right, its moves along the bottom, and nothing in between", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const built = deck(fromPack(demo, []), "xl");
    const [page, ...rest] = built;
    const shownCounters = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    expect(at(page!, "4,0")).toBe(`metric:${shownCounters[0]![0]}`);
    expect(at(page!, "5,0")).toBe(`metric:${shownCounters[1]![0]}`);
    expect(at(page!, "6,0")).toBe(`metric:${Object.keys(demo.resources ?? {})[0]}`);
    expect(at(page!, "1,3")).toBe(`press:${Object.keys(demo.moves ?? {})[0]}`);
    // The demo pack names no tool, so the setups row stays empty rather
    // than taking a move that has a row of its own.
    expect(at(page!, "1,2")).toBe("");
    expect(at(page!, "7,3")).toBe("turn:next");
    // Page two is the utility page, the same one the generic profile ends on.
    expect(rest).toHaveLength(1);
    expect(grid(built.at(-1)!, "xl")).toEqual(grid(deck(null, "xl").at(-1)!, "xl"));
  });

  it("fills an XL's three pools from their own queues before any of them spills", () => {
    const [first, second, third, ...rest] = deck(synthetic, "xl");
    expect(rest).toHaveLength(0);
    // Page one is full: eight counters across the top right, seven setups
    // on the third row, six moves along the bottom with the last cell spent
    // going on.
    expect(grid(first!, "xl")).toEqual([
      ["connect", "run", "undo", "clock", "metric:count0", "metric:count1", "metric:count2", "metric:count3"],
      ["next", "metric:latest", "metric:unit", "metric:score", "metric:count4", "metric:count5", "metric:count6", "metric:count7"],
      ["roll", "setup", "setup", "setup", "setup", "setup", "setup", "setup"],
      ["finish", "press:move0", "press:move1", "press:move2", "press:move3", "press:move4", "press:move5", "turn:next"],
    ]);
    // Page two wears the same frame, and the way back takes the cell the
    // moves had on page one.
    expect(grid(second!, "xl")).toEqual([
      ["connect", "run", "undo", "clock", "metric:count8", "metric:count9", "metric:count10", "metric:count11"],
      ["next", "metric:latest", "metric:unit", "metric:score", "", "", "", ""],
      // The one move left over takes a free setups cell, but only once
      // every setup has one.
      ["roll", "setup", "setup", "press:move11", "", "", "", ""],
      ["finish", "press:move6", "press:move7", "press:move8", "press:move9", "press:move10", "turn:previous", "turn:next"],
    ]);
    // The last run page still carries a way on, because the utility page
    // follows it.
    expect(at(second!, "7,3")).toBe("turn:next");
    expect(at(third!, "7,3")).toBe("install");
  });

  it("spills an XL's counters into the rows below once the top right is full", () => {
    // Twelve counters and no setups or moves: four counters over from the
    // numbers pool, and the setups row is where they go.
    const [page] = deck({ ...synthetic, moves: [], setups: [] }, "xl");
    expect(grid(page!, "xl")[2]).toEqual(["roll", "metric:count8", "metric:count9", "metric:count10", "metric:count11", "", "", ""]);
  });

  it("pages an XL under the same frame, and spills the moves into the rows above", () => {
    const [first, second, third, ...rest] = deck(crowded, "xl");
    expect(rest).toHaveLength(0);
    // The frame is the frame on every page of the run's, which is every
    // page but the last.
    for (const page of [first!, second!]) {
      expect(at(page, "0,1")).toBe("next");
      expect(at(page, "0,3")).toBe("finish");
      expect(at(page, "3,1")).toBe("metric:score");
    }
    // Two counters and then nothing, so the moves take the free number
    // cells rather than leaving half the deck empty.
    expect(at(first!, "4,0")).toBe("metric:one");
    expect(at(first!, "5,0")).toBe("metric:two");
    expect(at(first!, "1,3")).toBe("press:move0");
    // The setups row is free and the moves reach it before the numbers.
    expect(at(first!, "1,2")).toBe("press:move6");
    expect(at(first!, "6,0")).toBe("press:move13");
    expect(at(first!, "7,3")).toBe("turn:next");
    // The way back sits beside the way on, and the last page, which is the
    // utility page, grows no turn pointing at nothing.
    expect(at(second!, "6,3")).toBe("turn:previous");
    expect(at(second!, "7,3")).toBe("turn:next");
    expect(at(third!, "6,3")).toBe("turn:previous");
    expect(at(third!, "7,3")).toBe("install");
  });

  it("holds the same shape on a Stream Deck at five by three", () => {
    const [page, second, ...rest] = deck(null, "sd");
    expect(rest).toHaveLength(0);
    // The run along the top and down the left, the score pinned, and the
    // other two readouts leading the numbers queue because a pack with
    // counters of its own wants those two cells more.
    expect(grid(page!, "sd")).toEqual([
      ["connect", "run", "undo", "clock", "metric:score"],
      ["next", "roll", "finish", "metric:latest", "metric:unit"],
      ["", "", "", "", "turn:next"],
    ]);
    // The last page is the keys that are not about the run, in the right
    // two columns around the way back, and nothing else on the five by three.
    expect(grid(second!, "sd")).toEqual([
      ["connect", "run", "", "open:rules", "open:guide"],
      ["", "", "open:dock", "open:run", "open:newrun"],
      ["", "", "autoroll", "turn:previous", "install"],
    ]);
    for (const cell of others("sd", corner("sd"))) expect(at(second!, cell), cell).toBe("");
  });

  it("gives a Stream Deck the pack's moves along the bottom and its numbers beside them", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const [page] = deck(fromPack(demo, []), "sd");
    // The bottom row is the moves, with the fourth cell theirs on page one
    // because there is nowhere to go back to.
    expect(at(page!, "0,2")).toBe(`press:${Object.keys(demo.moves ?? {})[0]}`);
    expect(at(page!, "1,2")).toBe(`press:${Object.keys(demo.moves ?? {})[1]}`);
    // The two readouts lead the numbers queue, so the pack's own counters
    // follow them and spill along the bottom row.
    expect(at(page!, "3,1")).toBe("metric:latest");
    expect(at(page!, "4,1")).toBe("metric:unit");
    const shownCounters = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    expect(at(page!, "2,2")).toBe(`metric:${shownCounters[0]![0]}`);
  });

  it("turns a Stream Deck's pages from the two cells a frame can spare", () => {
    const pages = deck(crowded, "sd");
    const [first, second] = pages;
    expect(at(first!, "4,2")).toBe("turn:next");
    expect(at(first!, "3,2")).not.toBe("turn:previous");
    expect(at(second!, "3,2")).toBe("turn:previous");
    expect(at(second!, "4,2")).toBe("turn:next");
    // Nothing that is not about the run in hand is on a run page: every
    // Open key is on the last one.
    for (const page of pages.slice(0, -1)) {
      const opens = Object.keys(page)
        .map((cell) => at(page, cell))
        .filter((says) => says.startsWith("open:"));
      expect(opens).toEqual([]);
    }
  });

  it("lays a Mini and a + down in order, because neither has room for a frame", () => {
    expect(FRAMES.mini).toBeUndefined();
    expect(FRAMES.plus).toBeUndefined();
    const mini = deck(null, "mini");
    const [page] = mini;
    expect(at(page!, "0,0")).toBe("connect");
    expect(at(page!, "1,0")).toBe("run");
    expect(at(page!, "2,1")).toBe("turn:next");
    // Both end on the utility page all the same: the way back, then the
    // four keys that are not about the run.
    const last = mini[mini.length - 1]!;
    expect(["0,0", "1,0", "2,0", "0,1", "1,1", "2,1"].map((cell) => at(last, cell))).toEqual([
      "turn:previous",
      "install",
      "open:guide",
      "open:newrun",
      "open:dock",
      "",
    ]);
    const plus = deck(null, "plus");
    const end = plus[plus.length - 1]!;
    expect(["0,0", "1,0", "2,0", "3,0", "0,1"].map((cell) => at(end, cell))).toEqual([
      "turn:previous",
      "install",
      "open:guide",
      "open:newrun",
      "open:dock",
    ]);
  });

  it("repeats a +'s dials on the utility page, the way it does on every other", () => {
    const built = profile(specsFor(null, { slug: "test", name: "Test" }, "plus")[0]!);
    const wheels = Object.values(built.files)
      .filter((file): file is PageFile => "Controllers" in file)
      .map((file) => file.Controllers.find((c) => c.Type === "Encoder"))
      .filter((c) => c !== undefined);
    expect(wheels).toHaveLength(pages(built).length);
    for (const wheel of wheels) expect(Object.keys(wheel.Actions ?? {})).toEqual(["0,0", "1,0", "2,0", "3,0"]);
  });

  it("frames every base key or queues it, and never both", () => {
    const said = (key: { action: string; settings?: Record<string, unknown> }) => JSON.stringify(key);
    for (const [device, frame] of Object.entries(FRAMES)) {
      const queued = POOLS.flatMap((pool) => [...frame.extras[pool].first, ...frame.extras[pool].last]);
      const held = [...frame.fixed.map((f) => said(f.key)), ...queued.map(said)];
      // A run page carries the base keys that are about the run in hand.
      // The rest are on the utility page, and nowhere else.
      const utility = frame.utility.map((u) => said(u.key));
      expect([...held, ...utility.filter((key) => !held.includes(key))].sort(), device).toEqual(
        [...new Set([...BASE.map(said), ...utility])].sort(),
      );
      expect(
        held.filter((key) => !BASE.map(said).includes(key)),
        device,
      ).toEqual([]);
      // Connect and the run are the only two the utility page repeats: a
      // deck that is not connected says nothing wherever you are standing.
      expect(
        utility.filter((key) => held.includes(key)),
        device,
      ).toEqual([said({ action: "connect" }), said({ action: "run" })]);
    }
  });

  it("puts a key in one cell per page, on every page of every frame", () => {
    for (const [device, frame] of Object.entries(FRAMES)) {
      const cells = [...frame.fixed.map((f) => f.at), ...POOLS.flatMap((pool) => frame.pools[pool]), frame.turns.next];
      expect(new Set(cells).size, device).toBe(cells.length);
      // The way back takes a pool cell, which is what gives the moves one
      // more cell on the first page than on any other.
      expect(
        POOLS.flatMap((pool) => frame.pools[pool]),
        device,
      ).toContain(frame.turns.previous);
      // The grid holds it all, with nothing left over.
      expect(cells.length, device).toBe(DEVICES[device as "xl" | "sd"].columns * DEVICES[device as "xl" | "sd"].rows);
      const utility = frame.utility.map((u) => u.at);
      expect(new Set(utility).size, device).toBe(utility.length);
      expect(utility, device).not.toContain(frame.turns.previous);
    }
  });

  it("lays every key inside its own deck's grid", () => {
    for (const { spec, built } of all) {
      const { columns, rows, dials } = DEVICES[spec.device];
      for (const { controller, position } of placed(built)) {
        const [column, row] = position.split(",").map(Number);
        const width = controller === "Encoder" ? dials : columns;
        const height = controller === "Encoder" ? 1 : rows;
        expect(column, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(width);
        expect(row, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(height);
        expect(column).toBeGreaterThanOrEqual(0);
        expect(row).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("puts one thing in one place", () => {
    for (const { spec, built } of all) {
      const seen = new Set<string>();
      for (const { page, controller, position } of placed(built)) {
        const where = `${page} ${controller} ${position}`;
        expect(seen.has(where), `${spec.slug}-${spec.device} doubles up on ${where}`).toBe(false);
        seen.add(where);
      }
    }
  });

  it("places nothing but our own actions and the app's page turns", () => {
    const manifest = JSON.parse(readFileSync(path("streamdeck/com.scrthq.runlog.sdPlugin/manifest.json"), "utf8")) as {
      Actions: Array<{ UUID: string }>;
    };
    const allowed = new Set([
      ...manifest.Actions.map((a) => a.UUID),
      "com.elgato.streamdeck.page.next",
      "com.elgato.streamdeck.page.previous",
    ]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        expect(allowed.has(action.UUID), `${spec.slug}-${spec.device} places ${action.UUID}`).toBe(true);
      }
    }
  });

  it("sets each key to what its own settings type allows", () => {
    // The shapes are `PressTarget`, `MetricField`, `SetupSettings` and
    // `NextSettings` in `streamdeck/src/state.ts`. A key set to something
    // the plugin cannot read draws "Set up" for ever and says nothing
    // about why.
    const fields = new Set(["score", "unit", "latest", "leader"]);
    const kinds = new Set(["move", "answer"]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        const settings = action.Settings;
        const where = `${spec.slug}-${spec.device} ${action.UUID}`;
        if (action.UUID === "com.scrthq.runlog.metric") {
          const field = settings["field"] as string | Record<string, string>;
          if (typeof field === "string") expect(fields.has(field), where).toBe(true);
          else
            expect(Object.keys(field), where).toSatisfy(
              (keys: string[]) => keys.length === 1 && ["counter", "resource"].includes(keys[0]!),
            );
        } else if (action.UUID === "com.scrthq.runlog.press") {
          const target = settings["target"] as { kind: string; id?: string };
          expect(kinds.has(target.kind), where).toBe(true);
          if (target.kind === "move") expect(typeof target.id, where).toBe("string");
        } else if (action.UUID === "com.scrthq.runlog.setup") {
          expect(Object.keys(settings["setup"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.command") {
          expect(Object.keys(settings["command"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.open") {
          expect(["run", "guide", "rules", "newrun", "dock"], where).toContain(settings["target"]);
        } else {
          expect(settings, where).toEqual({});
        }
      }
    }
  });

  it("sets no Metric key to the clock, on any deck of any of the forty-four", () => {
    // A picker never offers what a dedicated key does, and a generator is a
    // picker: the Clock action is on the frame, so no readout of it is.
    for (const { spec, built } of all) {
      const clocks = placed(built).filter((p) => p.action.UUID === "com.scrthq.runlog.metric" && p.action.Settings["field"] === "clock");
      expect(clocks, `${spec.slug}-${spec.device}`).toHaveLength(0);
    }
  });

  it("gives a + its dials, and no other deck one", () => {
    for (const { spec, built } of all) {
      const wheels = placed(built).filter((p) => p.controller === "Encoder");
      if (spec.device !== "plus") {
        expect(wheels, `${spec.slug}-${spec.device}`).toHaveLength(0);
        continue;
      }
      // Only Next, Metric and Clock declare `Encoder` in the manifest.
      for (const { action } of wheels) {
        expect(["com.scrthq.runlog.next", "com.scrthq.runlog.metric", "com.scrthq.runlog.clock"]).toContain(action.UUID);
      }
    }
  });

  it("gives every profile the run, the guide, a new run, the dock and the rules", () => {
    for (const { spec, built } of all) {
      const targets = [
        ...new Set(
          placed(built)
            .filter((p) => p.action.UUID === "com.scrthq.runlog.open")
            .map((p) => (p.action.Settings as { target: string }).target),
        ),
      ].sort();
      const common = ["dock", "guide", "newrun", "run"];
      // A framed deck has all five on its utility page, whatever pack it
      // was laid out for. A Mini and a + lay their keys down in order, so
      // the rules key is a pack's alone there: the generic layout has no
      // pack behind it to open.
      const framed = spec.device === "xl" || spec.device === "sd";
      const rules = framed || spec.slug !== "runlog";
      expect(targets, `${spec.slug}-${spec.device}`).toEqual(rules ? [...common, "rules"].sort() : common);
    }
  });

  it("puts the keys that are not about the run on the last page of every profile", () => {
    for (const { spec, built } of all) {
      const last = pages(built).at(-1)!;
      const said = Object.keys(last).map((cell) => at(last, cell));
      expect(said, `${spec.slug}-${spec.device}`).toContain("install");
      for (const target of ["guide", "newrun", "dock"]) {
        expect(said, `${spec.slug}-${spec.device}`).toContain(`open:${target}`);
      }
      // The last page of a profile turns back and nowhere on.
      expect(
        said.filter((says) => says === "turn:next"),
        `${spec.slug}-${spec.device}`,
      ).toHaveLength(0);
      // And the Install key is on that page alone, not scattered through
      // the pack's own.
      const installs = placed(built).filter((p) => p.action.UUID === "com.scrthq.runlog.install");
      expect(installs, `${spec.slug}-${spec.device}`).toHaveLength(1);
    }
  });

  it("carries exactly the pack's moves, its shown counters, its resources and its tool's setups", () => {
    // A key set to a move the pack renamed last month is dead on somebody's
    // deck and says nothing about why, so what is placed is held against
    // the pack itself rather than counted.
    for (const { slug, pack, setups } of shipped) {
      if (!pack) continue;
      for (const { spec, built } of all.filter((b) => b.spec.slug === slug)) {
        const settings = placed(built).map((p) => p.action.Settings);
        const where = `${spec.slug}-${spec.device}`;

        const moves = settings.filter((s) => (s["target"] as { kind?: string } | undefined)?.kind === "move");
        expect(moves.map((s) => (s["target"] as { id: string }).id).sort(), where).toEqual(Object.keys(pack.moves ?? {}).sort());

        const numbers = (which: "counter" | "resource") =>
          settings
            .filter((s) => typeof s["field"] === "object" && which in (s["field"] as object))
            .map((s) => (s["field"] as Record<string, string>)[which]!);
        const shownCounters = Object.entries(pack.counters ?? {})
          .filter(([, c]) => !c.hidden)
          .map(([id]) => id);
        expect(numbers("counter").sort(), where).toEqual(shownCounters.sort());
        expect(numbers("resource").sort(), where).toEqual(Object.keys(pack.resources ?? {}).sort());

        const handedOut = settings
          .filter((s) => s["setup"] ?? s["command"])
          .map((s) => ((s["setup"] ?? s["command"]) as { id: string }).id);
        expect(handedOut.sort(), where).toEqual(setups.map((s) => s.id).sort());
      }
    }
  });

  it("gives the demo pack no setup keys, because it names no tool", () => {
    const built = all.find(({ spec }) => spec.slug === "demo" && spec.device === "xl")!.built;
    expect(placed(built).filter((p) => p.action.UUID === "com.scrthq.runlog.setup")).toHaveLength(0);
  });

  it("offers a deck only to a pack with something of its own to put on one", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(hasKeys(demo)).toBe(true);
    expect(hasKeys({ ...demo, moves: undefined, counters: undefined, resources: undefined })).toBe(false);
    expect(hasKeys({ ...demo, counters: undefined, resources: undefined })).toBe(true);
  });

  it("names a profile after the pack, and a Marketplace one after its id", () => {
    // The shipped forty-four are written under the short slug their file
    // is named by, which the generator puts on each spec; a pack from the
    // Marketplace has no such file, so its id is what names the download.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(specs(demo, [], "xl")).toEqual([
      { slug: demo.id, device: "xl", name: shippedName(demo.title), keys: expect.anything(), zones: expect.anything() },
    ]);
    expect(specs(null, []).map((s) => `${s.slug}-${s.device}`)).toEqual(["runlog-xl", "runlog-sd", "runlog-mini", "runlog-plus"]);
  });

  it("marks every profile it makes for a pack, and leaves the generic one alone", () => {
    // One pack, one name, wherever the profile came from: the four the
    // plugin ships, the one the Install key builds, and the download off
    // the pack's page. The mark is spelled in one place and put on by the
    // generator, so no caller can hand out a bare title by mistake.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(shippedName(demo.title)).toBe(`${demo.title} (Runlog)`);
    for (const spec of specs(demo, [])) expect(spec.name).toBe(shippedName(demo.title));
    for (const spec of specsFor(fromPack(demo, []), { slug: "whatever", name: demo.title })) {
      expect(spec.name).toBe(shippedName(demo.title));
    }
    // And it is in the file, which is where the Stream Deck app reads it.
    const written = profile(specs(demo, [], "xl")[0]!).files["manifest.json"] as RootFile;
    expect(written.Name).toBe(shippedName(demo.title));

    // The generic layout is nobody's pack: it says what it is.
    for (const spec of specs(null, [])) expect(spec.name).toBe("Runlog");
    expect(specsFor(null, GENERIC, "xl")[0]!.name).toBe("Runlog");
    expect(all.find(({ spec }) => spec.slug === "demo")!.spec.name).toBe(shippedName(demo.title));
    expect(all.find(({ spec }) => spec.slug === "runlog")!.spec.name).toBe("Runlog");
  });

  it("lays a run's own offer out the way it lays the pack file out", () => {
    // The plugin follows runs, not packs. A pack from the Marketplace is
    // not on the deck's disk and never will be, so a profile for it is
    // built from what the run publishes about itself: the moves, the
    // trackers, and the setups for the tool. The two adapters are held
    // against each other here, because the day they disagree is the day a
    // key built from a run presses something the shipped profile does not.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const setup = (id: string, title: string): Setup => ({
      kind: "setup",
      schemaVersion: 1,
      id: `com.example.setups.${id}`,
      version: "1.0.0",
      title,
      tool: "ExampleTool",
      ops: [{ op: "flag.set", args: { name: id } }],
    });
    // One of each, because which key a setup takes is the one thing the
    // two adapters have to agree about: a warp goes to a Command key and
    // everything else to an Apply setup key.
    const setups = [setup("starter", "Starter kit"), setup("summit", "Warp to the summit")];

    // The offer as the page publishes it: every setup in `setups`, and the
    // same list again in `commands` less whatever the wire would drop,
    // which is nothing here. A hidden counter is published by neither.
    const shown = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    const offer = {
      moves: Object.keys(demo.moves ?? {}).map((id) => ({ id, label: id })),
      trackers: [
        ...shown.map(([id]) => ({ id, kind: "counter" as const, label: id })),
        ...Object.keys(demo.resources ?? {}).map((id) => ({ id, kind: "resource" as const, label: id })),
      ],
      setups: setups.map(({ id, title }) => ({ id, title })),
      commands: setups.map(({ id, title }) => ({ id, title })),
    };

    expect(packKeys(fromOffer(offer))).toEqual(packKeys(fromPack(demo, setups)));
    // And the same profile, byte for byte, under the same name and slug.
    const named = { slug: demo.id, name: demo.title };
    expect([...container(profile(specsFor(fromOffer(offer), named, "xl")[0]!))]).toEqual([
      ...container(profile(specs(demo, setups, "xl")[0]!)),
    ]);
  });

  it("reads the layout the engine publishes, field for field", () => {
    // `Laid` is a copy of the engine's shape, the way `Offered` is a copy
    // of the offer's: this package is imported by a browser and takes
    // nothing from either app at run time. The copy is only worth anything
    // while it still matches, so the engine's own type is assigned to it
    // here and a field renamed over there fails this.
    const published: NonNullable<LiveSnapshot["layout"]> = {
      moves: [{ id: "settle", label: "Settle" }],
      counters: [{ id: "marks", label: "Marks" }],
      resources: [{ id: "clay", label: "Clay" }],
    };
    const laid: Laid = published;

    const keyed = fromOffer({}, laid);
    expect(keyed.moves.map((m) => m.id)).toEqual(["settle"]);
    expect(keyed.counters.map((c) => c.id)).toEqual(["marks"]);
    expect(keyed.resources.map((r) => r.id)).toEqual(["clay"]);
  });

  it("lays out the pack's whole layout where the snapshot carries one, not the moment's offer", () => {
    // The offer is the state's view: a move behind a shut gate is not in
    // it, and a profile built from it would be missing a key until the
    // next time somebody built one. The layout is the pack itself.
    const keyed = fromOffer(
      {
        moves: [{ id: "push-on" }],
        trackers: [{ id: "marks", kind: "counter" }],
        setups: [{ id: "com.example.setups.starter", title: "Starter kit" }],
      },
      {
        moves: [{ id: "push-on" }, { id: "hold" }],
        counters: [{ id: "marks" }, { id: "scars" }],
        resources: [{ id: "stock" }],
      },
    );

    expect(keyed.moves.map((m) => m.id)).toEqual(["push-on", "hold"]);
    expect(keyed.counters.map((c) => c.id)).toEqual(["marks", "scars"]);
    expect(keyed.resources.map((r) => r.id)).toEqual(["stock"]);
    // The setups are the offer's either way: a layout carries none.
    expect(keyed.setups.map((s) => s.id)).toEqual(["com.example.setups.starter"]);
  });

  it("reads the offer alone where a page publishes no layout", () => {
    const offer = {
      moves: [{ id: "push-on" }],
      trackers: [
        { id: "marks", kind: "counter" as const },
        { id: "stock", kind: "resource" as const },
      ],
    };
    expect(fromOffer(offer)).toEqual(fromOffer(offer, null));
    expect(fromOffer(offer).moves.map((m) => m.id)).toEqual(["push-on"]);
    expect(fromOffer(offer).resources.map((r) => r.id)).toEqual(["stock"]);
  });

  it("gives a setup on both of the offer's lists one key, not two", () => {
    // `commands` on a run's offer is not the warps: it is every setup
    // again, offered the other way round. A profile has to pick one key
    // per setup, so the ones that read as warps become Command keys and
    // the rest Apply setup keys, and nothing is laid down twice.
    const both = [
      { id: "com.example.setups.starter", title: "Starter kit" },
      { id: "com.example.setups.summit", title: "Warp to the summit" },
    ];
    const keyed = fromOffer({ setups: both, commands: both });
    expect(keyed.setups.map((s) => s.id)).toEqual(["com.example.setups.starter"]);
    expect(keyed.commands.map((s) => s.id)).toEqual(["com.example.setups.summit"]);
  });

  it("builds the same bytes twice, so regenerating is not a diff", () => {
    for (const { spec } of all) {
      const twice = [container(profile(spec)), container(profile(spec))];
      expect([...twice[0]!], `${spec.slug}-${spec.device}`).toEqual([...twice[1]!]);
    }
  });

  it("rebuilds every profile committed under the plugin, byte for byte", () => {
    // A `.streamDeckProfile` is generated and committed rather than built
    // at install time, so a layout change nobody regenerated for leaves a
    // stale zip next to the source that no longer agrees with it.
    expect(all).toHaveLength(44);
    for (const { spec, built } of all) {
      const committed = readFileSync(path(`streamdeck/com.scrthq.runlog.sdPlugin/profiles/${spec.slug}-${spec.device}.streamDeckProfile`));
      expect(Buffer.from(container(built)).equals(committed), `${spec.slug}-${spec.device}`).toBe(true);
    }
  });
});
