import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { loadPackText, loadSetupText, type Pack, type Setup } from "@runlog/rules-schema";
// A type and nothing else: it is erased, so the engine does not follow this
// package into a browser. What it buys is the pin below, where the layout
// the page publishes has to still be the layout a profile is laid out from.
import type { LiveSnapshot } from "@runlog/engine";

import { PACK_PROFILES } from "../../../streamdeck/src/profiles.ts";
import { BASE, DEVICES, DEVICE_IDS, FRAMES } from "./layouts.ts";
import {
  container,
  framedPages,
  fromOffer,
  fromPack,
  hasKeys,
  packKeys,
  paginate,
  profile,
  specs,
  specsFor,
  type Built,
  type Keyed,
  type Laid,
  type StoredAction,
} from "./profiles.ts";

/**
 * The generator, held against the packs it reads and the grids its output
 * has to fit on.
 *
 * Nobody reads a `.streamDeckProfile`. It is a zip of compact JSON that
 * goes out with a release or off a pack's page and turns up on somebody's
 * desk, and the two ways it goes wrong, a key off the edge of a Mini and a
 * move whose id the pack renamed last month, both look to whoever imported
 * it like the plugin being broken. So the layout is held to the grid and to
 * the pack here, where a mistake costs a test run rather than a support
 * thread.
 *
 * The last and largest check is that this package rebuilds the forty-four
 * files committed under the plugin, byte for byte. Those are generated by
 * `streamdeck/design/profiles.mjs`, which is a Node script over this code;
 * proving the package alone reproduces them is what says a browser
 * building a profile for a Marketplace pack is building the same thing.
 */

const repo = new URL("../../../", import.meta.url);
const path = (rest: string) => fileURLToPath(new URL(rest, repo));

/** Every setup written for a tool, by title, the way the app's picker lists them. */
function setupsFor(tool: string | undefined): Setup[] {
  if (!tool) return [];
  const dir = path("packs/setups");
  const out: Setup[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".yaml"))) {
    const parsed = loadSetupText(readFileSync(`${dir}/${file}`, "utf8"), "yaml");
    if (parsed.ok && parsed.setup.tool.toLowerCase() === tool.toLowerCase()) out.push(parsed.setup);
  }
  return out.sort((a, b) => a.title.localeCompare(b.title));
}

/** The tool a pack is driven by, from the control profile written for it. */
function toolFor(packId: string): string | undefined {
  const dir = path("packs/profiles");
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const written = JSON.parse(readFileSync(`${dir}/${file}`, "utf8")) as { pack?: string; tool?: string };
    if (written.pack === packId) return written.tool;
  }
  return undefined;
}

/**
 * The layouts the plugin ships, read the way the generator reads them.
 *
 * The slug each pack ships under comes from `streamdeck/src/profiles.ts`,
 * the table the generator writes and the plugin switches through, rather
 * than from a second copy of the naming rule kept here.
 */
const shipped: Array<{ slug: string; pack: Pack | null; setups: Setup[] }> = [{ slug: "runlog", pack: null, setups: [] }];
for (const file of ["packs/demo/pack.yaml", ...readdirSync(path("packs/sketches")).map((f) => `packs/sketches/${f}`)]) {
  if (!file.endsWith(".yaml")) continue;
  const parsed = loadPackText(readFileSync(path(file), "utf8"), "yaml");
  if (!parsed.ok) continue;
  const slug = PACK_PROFILES[parsed.pack.id];
  if (slug) shipped.push({ slug, pack: parsed.pack, setups: setupsFor(toolFor(parsed.pack.id)) });
}

/** Every layout on every deck, built, with the slug it ships under. */
const all = shipped.flatMap(({ slug, pack, setups }) =>
  specs(pack, setups).map((spec) => ({ spec: { ...spec, slug }, built: profile({ ...spec, slug }) })),
);

/** Every action on every page of a built profile, with the page and position it sits at. */
function placed(built: Built): Array<{ page: string; controller: string; position: string; action: StoredAction }> {
  const out = [];
  for (const [page, file] of Object.entries(built.files)) {
    if (!("Controllers" in file)) continue;
    for (const controller of file.Controllers) {
      for (const [position, action] of Object.entries(controller.Actions ?? {})) {
        out.push({ page, controller: controller.Type, position, action });
      }
    }
  }
  return out;
}

/** Each page's keys, in page order. The empty default page carries none and is left out. */
function pages(built: Built): Array<Record<string, StoredAction>> {
  const out: Array<Record<string, StoredAction>> = [];
  for (const file of Object.values(built.files)) {
    if (!("Controllers" in file)) continue;
    const keypad = file.Controllers.find((c) => c.Type === "Keypad");
    if (keypad?.Actions) out.push(keypad.Actions);
  }
  return out;
}

/**
 * What sits in one cell, short enough to write a grid out in a test.
 *
 * The action's own last word, with whatever the key is set to after it, and
 * `turn:` for the app's own page keys, whose last word is `next` as well.
 */
function at(page: Record<string, StoredAction>, cell: string): string {
  const action = page[cell];
  if (!action) return "";
  const name = action.UUID.split(".").pop()!;
  if (action.UUID.startsWith("com.elgato.")) return `turn:${name}`;
  const settings = action.Settings;
  if (name === "metric") {
    const field = settings["field"];
    return `metric:${typeof field === "string" ? field : Object.values(field as Record<string, string>)[0]}`;
  }
  if (name === "open") return `open:${String(settings["target"])}`;
  if (name === "press") return `press:${(settings["target"] as { id: string }).id}`;
  return name;
}

/** A pack with more moves than a page holds and two numbers, for the paging rules. */
const crowded: Keyed = {
  moves: Array.from({ length: 20 }, (_, i) => ({ id: `move${i}` })),
  counters: [{ id: "one" }, { id: "two" }],
  resources: [],
  setups: [],
  commands: [],
};

/** One layout, built for one deck, as its pages. */
const deck = (keyed: Keyed | null, device: "xl" | "sd" | "mini" | "plus") =>
  pages(profile(specsFor(keyed, { slug: "test", name: "Test" }, device)[0]!));

describe("a deck laid out for a pack", () => {
  it("knows how big each deck is", () => {
    // Written out rather than taken from `DEVICES`, which is the table
    // under test: the grid check below reads the same numbers the layout
    // was built from, so without this it would pass on any pair of them.
    // These are the SDK's, from the `DeviceType` enumeration in
    // @elgato/schemas.
    expect(DEVICES.xl).toMatchObject({ type: 2, columns: 8, rows: 4, dials: 0 });
    expect(DEVICES.sd).toMatchObject({ type: 0, columns: 5, rows: 3, dials: 0 });
    expect(DEVICES.mini).toMatchObject({ type: 1, columns: 3, rows: 2, dials: 0 });
    expect(DEVICES.plus).toMatchObject({ type: 7, columns: 4, rows: 2, dials: 4 });
    expect(DEVICE_IDS).toEqual(Object.keys(DEVICES));
  });

  it("keeps a page's last slot for the way on, and its first for the way back", () => {
    const keys = Array.from({ length: 20 }, (_, i) => ({ action: `k${i}` }));
    // Six to a page: five on the first with the sixth spent going on, then
    // four with both turns, then the rest with only the way back.
    expect(paginate(keys, 6).map((p) => [p.back, p.more, p.keys.length])).toEqual([
      [false, true, 5],
      [true, true, 4],
      [true, true, 4],
      [true, true, 4],
      [true, false, 3],
    ]);
    // A layout that fits exactly grows no turn key pointing at nothing.
    expect(paginate(keys.slice(0, 6), 6)).toEqual([{ back: false, more: false, keys: keys.slice(0, 6) }]);
  });

  it("spills one queue into the other's cells once that one has run dry", () => {
    // A frame with one key pinned, two cells a hand's side and two an
    // eye's, and a turn cell at either end of the eye's.
    const frame = {
      fixed: [{ key: { action: "connect" }, at: "0,0" }],
      extras: { drive: { first: [], last: [] }, numbers: { first: [], last: [] } },
      drive: ["0,1", "0,2"],
      numbers: ["1,1", "1,2"],
      turns: { next: "1,2", previous: "1,1" },
    };
    const key = (action: string) => ({ action });

    // Nothing queued is still one page: the frame is the profile.
    expect(framedPages(frame, [], [])).toEqual([{ back: false, more: false, keys: { "0,0": { action: "connect" } } }]);

    // Numbers done, moves keep coming down the right.
    expect(framedPages(frame, [key("a"), key("b"), key("c")], [key("n")])).toEqual([
      {
        back: false,
        more: false,
        keys: { "0,0": key("connect"), "0,1": key("a"), "0,2": key("b"), "1,1": key("n"), "1,2": key("c") },
      },
    ]);

    // Moves done, numbers keep coming down the left.
    expect(framedPages(frame, [key("a")], [key("n"), key("o"), key("p")])).toEqual([
      {
        back: false,
        more: false,
        keys: { "0,0": key("connect"), "0,1": key("a"), "0,2": key("p"), "1,1": key("n"), "1,2": key("o") },
      },
    ]);

    // More than the four free cells hold: the last one goes on paging, and
    // the second page spends a cell coming back rather than going on.
    const long = framedPages(frame, [key("a"), key("b"), key("c"), key("d")], [key("n"), key("o")]);
    expect(long.map((p) => [p.back, p.more])).toEqual([
      [false, true],
      [true, false],
    ]);
    expect(Object.keys(long[0]!.keys).sort()).toEqual(["0,0", "0,1", "0,2", "1,1"]);
    expect(long[1]!.keys["0,1"]).toEqual(key("c"));
  });

  it("keeps the same frame under a hand on every page of an XL", () => {
    const [page] = deck(null, "xl");
    expect(page).toBeDefined();
    // The trio the hand rests on, the run above it, and Finish as far from
    // both as the grid goes.
    expect(at(page!, "0,1")).toBe("next");
    expect(at(page!, "1,1")).toBe("roll");
    expect(at(page!, "2,1")).toBe("undo");
    expect(at(page!, "0,0")).toBe("connect");
    expect(at(page!, "0,3")).toBe("finish");
    // The numbers the run works out, under the eye rather than the hand.
    expect(at(page!, "4,0")).toBe("metric:score");
    // Thirteen keys on a deck with thirty-two cells: one page, no turns,
    // and the cell a pack's rules would take left empty.
    expect(deck(null, "xl")).toHaveLength(1);
    expect(at(page!, "7,0")).toBe("");
  });

  it("gives an XL the pack's rules in the frame, its numbers right and its moves left", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const [page] = deck(fromPack(demo, []), "xl");
    expect(at(page!, "7,0")).toBe("open:rules");
    const shownCounters = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    expect(at(page!, "4,1")).toBe(`metric:${shownCounters[0]![0]}`);
    expect(at(page!, "1,2")).toBe(`press:${Object.keys(demo.moves ?? {})[0]}`);
  });

  it("pages an XL under the same frame, and spills the moves right once the numbers are done", () => {
    const [first, second, ...rest] = deck(crowded, "xl");
    expect(rest).toHaveLength(0);
    // The frame is the frame on both pages.
    for (const page of [first!, second!]) {
      expect(at(page, "0,1")).toBe("next");
      expect(at(page, "0,3")).toBe("finish");
      expect(at(page, "4,0")).toBe("metric:score");
      expect(at(page, "7,0")).toBe("open:rules");
    }
    // Two counters and then nothing, so the moves come down the right as
    // well as the left rather than leaving half the deck empty.
    expect(at(first!, "4,1")).toBe("metric:one");
    expect(at(first!, "5,1")).toBe("metric:two");
    expect(at(first!, "6,1")).toBe("press:move6");
    expect(at(first!, "7,3")).toBe("turn:next");
    // The way back sits beside where the way on was, and the last page
    // grows no turn pointing at nothing.
    expect(at(second!, "6,3")).toBe("turn:previous");
    expect(at(second!, "7,3")).toBe("");
  });

  it("queues what a Stream Deck has no cell to pin", () => {
    const [page] = deck(null, "sd");
    expect(deck(null, "sd")).toHaveLength(1);
    // Five by three has room to pin seven keys and no more, so the rest
    // queue: the two a hand wants mid-scene first.
    expect(at(page!, "2,0")).toBe("autoroll");
    expect(at(page!, "3,0")).toBe("clock");
    // The readouts queue behind whatever the pack keeps, which is nothing
    // in the generic profile.
    expect(at(page!, "4,1")).toBe("metric:unit");
    expect(at(page!, "4,2")).toBe("metric:clock");
    // And the frame is still the frame.
    expect(at(page!, "0,1")).toBe("next");
    expect(at(page!, "4,0")).toBe("metric:score");
    expect(at(page!, "0,2")).toBe("finish");
  });

  it("gives a Stream Deck the pack's own keys ahead of the keys nobody presses mid-scene", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const [page] = deck(fromPack(demo, []), "sd");
    // The pack's first move takes the first free cell after the two the
    // hand wants, and its first number takes the first free number cell.
    expect(at(page!, "3,1")).toBe(`press:${Object.keys(demo.moves ?? {})[0]}`);
    const shownCounters = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    expect(at(page!, "4,1")).toBe(`metric:${shownCounters[0]![0]}`);
  });

  it("turns a Stream Deck's pages from the two cells a frame can spare", () => {
    const pages = deck(crowded, "sd");
    const [first, second] = pages;
    expect(at(first!, "4,2")).toBe("turn:next");
    expect(at(first!, "3,2")).not.toBe("turn:previous");
    expect(at(second!, "3,2")).toBe("turn:previous");
    expect(at(second!, "4,2")).toBe("turn:next");
    // The Open keys wait behind every move the pack has, and the rules
    // behind them, so the last page is where all three land.
    const last = pages[pages.length - 1]!;
    const opens = Object.keys(last)
      .map((cell) => at(last, cell))
      .filter((says) => says.startsWith("open:"));
    expect(opens).toEqual(["open:run", "open:guide", "open:rules"]);
  });

  it("turns a Stream Deck's pages from the two cells a frame can spare", () => {
    const [first, second] = deck(crowded, "sd");
    expect(at(first!, "4,2")).toBe("turn:next");
    expect(at(first!, "3,2")).not.toBe("turn:previous");
    expect(at(second!, "3,2")).toBe("turn:previous");
    expect(at(second!, "4,2")).toBe("turn:next");
  });

  it("lays a Mini and a + down in order, because neither has room for a frame", () => {
    expect(FRAMES.mini).toBeUndefined();
    expect(FRAMES.plus).toBeUndefined();
    const [page] = deck(null, "mini");
    expect(at(page!, "0,0")).toBe("connect");
    expect(at(page!, "1,0")).toBe("run");
    expect(at(page!, "2,1")).toBe("turn:next");
  });

  it("frames every base key or queues it, and never both", () => {
    for (const [device, frame] of Object.entries(FRAMES)) {
      const said = (key: { action: string; settings?: Record<string, unknown> }) => JSON.stringify(key);
      const queued = [...frame.extras.drive.first, ...frame.extras.drive.last, ...frame.extras.numbers.first, ...frame.extras.numbers.last];
      const held = [...frame.fixed.map((f) => said(f.key)), ...queued.map(said)];
      expect(held.sort(), device).toEqual(BASE.map(said).sort());
    }
  });

  it("lays every key inside its own deck's grid", () => {
    for (const { spec, built } of all) {
      const { columns, rows, dials } = DEVICES[spec.device];
      for (const { controller, position } of placed(built)) {
        const [column, row] = position.split(",").map(Number);
        const width = controller === "Encoder" ? dials : columns;
        const height = controller === "Encoder" ? 1 : rows;
        expect(column, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(width);
        expect(row, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(height);
        expect(column).toBeGreaterThanOrEqual(0);
        expect(row).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("puts one thing in one place", () => {
    for (const { spec, built } of all) {
      const seen = new Set<string>();
      for (const { page, controller, position } of placed(built)) {
        const where = `${page} ${controller} ${position}`;
        expect(seen.has(where), `${spec.slug}-${spec.device} doubles up on ${where}`).toBe(false);
        seen.add(where);
      }
    }
  });

  it("places nothing but our own actions and the app's page turns", () => {
    const manifest = JSON.parse(readFileSync(path("streamdeck/com.scrthq.runlog.sdPlugin/manifest.json"), "utf8")) as {
      Actions: Array<{ UUID: string }>;
    };
    const allowed = new Set([
      ...manifest.Actions.map((a) => a.UUID),
      "com.elgato.streamdeck.page.next",
      "com.elgato.streamdeck.page.previous",
    ]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        expect(allowed.has(action.UUID), `${spec.slug}-${spec.device} places ${action.UUID}`).toBe(true);
      }
    }
  });

  it("sets each key to what its own settings type allows", () => {
    // The shapes are `PressTarget`, `MetricField`, `SetupSettings` and
    // `NextSettings` in `streamdeck/src/state.ts`. A key set to something
    // the plugin cannot read draws "Set up" for ever and says nothing
    // about why.
    const fields = new Set(["score", "unit", "clock", "latest", "leader"]);
    const kinds = new Set(["move", "answer"]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        const settings = action.Settings;
        const where = `${spec.slug}-${spec.device} ${action.UUID}`;
        if (action.UUID === "com.scrthq.runlog.metric") {
          const field = settings["field"] as string | Record<string, string>;
          if (typeof field === "string") expect(fields.has(field), where).toBe(true);
          else
            expect(Object.keys(field), where).toSatisfy(
              (keys: string[]) => keys.length === 1 && ["counter", "resource"].includes(keys[0]!),
            );
        } else if (action.UUID === "com.scrthq.runlog.press") {
          const target = settings["target"] as { kind: string; id?: string };
          expect(kinds.has(target.kind), where).toBe(true);
          if (target.kind === "move") expect(typeof target.id, where).toBe("string");
        } else if (action.UUID === "com.scrthq.runlog.setup") {
          expect(Object.keys(settings["setup"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.command") {
          expect(Object.keys(settings["command"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.open") {
          expect(["run", "guide", "rules", "newrun", "dock"], where).toContain(settings["target"]);
        } else {
          expect(settings, where).toEqual({});
        }
      }
    }
  });

  it("gives a + its dials, and no other deck one", () => {
    for (const { spec, built } of all) {
      const wheels = placed(built).filter((p) => p.controller === "Encoder");
      if (spec.device !== "plus") {
        expect(wheels, `${spec.slug}-${spec.device}`).toHaveLength(0);
        continue;
      }
      // Only Next, Metric and Clock declare `Encoder` in the manifest.
      for (const { action } of wheels) {
        expect(["com.scrthq.runlog.next", "com.scrthq.runlog.metric", "com.scrthq.runlog.clock"]).toContain(action.UUID);
      }
    }
  });

  it("gives every profile the run and the guide, and only a pack's the rules", () => {
    for (const { spec, built } of all) {
      // Once each, however many pages: a framed deck keeps its Open keys in
      // the frame, so they are on every page of one.
      const targets = [
        ...new Set(
          placed(built)
            .filter((p) => p.action.UUID === "com.scrthq.runlog.open")
            .map((p) => (p.action.Settings as { target: string }).target),
        ),
      ].sort();
      expect(targets, `${spec.slug}-${spec.device}`).toEqual(spec.slug === "runlog" ? ["guide", "run"] : ["guide", "rules", "run"]);
    }
  });

  it("carries exactly the pack's moves, its shown counters, its resources and its tool's setups", () => {
    // A key set to a move the pack renamed last month is dead on somebody's
    // deck and says nothing about why, so what is placed is held against
    // the pack itself rather than counted.
    for (const { slug, pack, setups } of shipped) {
      if (!pack) continue;
      for (const { spec, built } of all.filter((b) => b.spec.slug === slug)) {
        const settings = placed(built).map((p) => p.action.Settings);
        const where = `${spec.slug}-${spec.device}`;

        const moves = settings.filter((s) => (s["target"] as { kind?: string } | undefined)?.kind === "move");
        expect(moves.map((s) => (s["target"] as { id: string }).id).sort(), where).toEqual(Object.keys(pack.moves ?? {}).sort());

        const numbers = (which: "counter" | "resource") =>
          settings
            .filter((s) => typeof s["field"] === "object" && which in (s["field"] as object))
            .map((s) => (s["field"] as Record<string, string>)[which]!);
        const shownCounters = Object.entries(pack.counters ?? {})
          .filter(([, c]) => !c.hidden)
          .map(([id]) => id);
        expect(numbers("counter").sort(), where).toEqual(shownCounters.sort());
        expect(numbers("resource").sort(), where).toEqual(Object.keys(pack.resources ?? {}).sort());

        const handedOut = settings
          .filter((s) => s["setup"] ?? s["command"])
          .map((s) => ((s["setup"] ?? s["command"]) as { id: string }).id);
        expect(handedOut.sort(), where).toEqual(setups.map((s) => s.id).sort());
      }
    }
  });

  it("gives the demo pack no setup keys, because it names no tool", () => {
    const built = all.find(({ spec }) => spec.slug === "demo" && spec.device === "xl")!.built;
    expect(placed(built).filter((p) => p.action.UUID === "com.scrthq.runlog.setup")).toHaveLength(0);
  });

  it("offers a deck only to a pack with something of its own to put on one", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(hasKeys(demo)).toBe(true);
    expect(hasKeys({ ...demo, moves: undefined, counters: undefined, resources: undefined })).toBe(false);
    expect(hasKeys({ ...demo, counters: undefined, resources: undefined })).toBe(true);
  });

  it("names a profile after the pack, and a Marketplace one after its id", () => {
    // The shipped forty-four are written under the short slug their file
    // is named by, which the generator puts on each spec; a pack from the
    // Marketplace has no such file, so its id is what names the download.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(specs(demo, [], "xl")).toEqual([
      { slug: demo.id, device: "xl", name: demo.title, keys: expect.anything(), zones: expect.anything() },
    ]);
    expect(specs(null, []).map((s) => `${s.slug}-${s.device}`)).toEqual(["runlog-xl", "runlog-sd", "runlog-mini", "runlog-plus"]);
  });

  it("lays a run's own offer out the way it lays the pack file out", () => {
    // The plugin follows runs, not packs. A pack from the Marketplace is
    // not on the deck's disk and never will be, so a profile for it is
    // built from what the run publishes about itself: the moves, the
    // trackers, and the setups for the tool. The two adapters are held
    // against each other here, because the day they disagree is the day a
    // key built from a run presses something the shipped profile does not.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const setup = (id: string, title: string): Setup => ({
      kind: "setup",
      schemaVersion: 1,
      id: `com.example.setups.${id}`,
      version: "1.0.0",
      title,
      tool: "ExampleTool",
      ops: [{ op: "flag.set", args: { name: id } }],
    });
    // One of each, because which key a setup takes is the one thing the
    // two adapters have to agree about: a warp goes to a Command key and
    // everything else to an Apply setup key.
    const setups = [setup("starter", "Starter kit"), setup("summit", "Warp to the summit")];

    // The offer as the page publishes it: every setup in `setups`, and the
    // same list again in `commands` less whatever the wire would drop,
    // which is nothing here. A hidden counter is published by neither.
    const shown = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    const offer = {
      moves: Object.keys(demo.moves ?? {}).map((id) => ({ id, label: id })),
      trackers: [
        ...shown.map(([id]) => ({ id, kind: "counter" as const, label: id })),
        ...Object.keys(demo.resources ?? {}).map((id) => ({ id, kind: "resource" as const, label: id })),
      ],
      setups: setups.map(({ id, title }) => ({ id, title })),
      commands: setups.map(({ id, title }) => ({ id, title })),
    };

    expect(packKeys(fromOffer(offer))).toEqual(packKeys(fromPack(demo, setups)));
    // And the same profile, byte for byte, under the same name and slug.
    const named = { slug: demo.id, name: demo.title };
    expect([...container(profile(specsFor(fromOffer(offer), named, "xl")[0]!))]).toEqual([
      ...container(profile(specs(demo, setups, "xl")[0]!)),
    ]);
  });

  it("reads the layout the engine publishes, field for field", () => {
    // `Laid` is a copy of the engine's shape, the way `Offered` is a copy
    // of the offer's: this package is imported by a browser and takes
    // nothing from either app at run time. The copy is only worth anything
    // while it still matches, so the engine's own type is assigned to it
    // here and a field renamed over there fails this.
    const published: NonNullable<LiveSnapshot["layout"]> = {
      moves: [{ id: "settle", label: "Settle" }],
      counters: [{ id: "marks", label: "Marks" }],
      resources: [{ id: "clay", label: "Clay" }],
    };
    const laid: Laid = published;

    const keyed = fromOffer({}, laid);
    expect(keyed.moves.map((m) => m.id)).toEqual(["settle"]);
    expect(keyed.counters.map((c) => c.id)).toEqual(["marks"]);
    expect(keyed.resources.map((r) => r.id)).toEqual(["clay"]);
  });

  it("lays out the pack's whole layout where the snapshot carries one, not the moment's offer", () => {
    // The offer is the state's view: a move behind a shut gate is not in
    // it, and a profile built from it would be missing a key until the
    // next time somebody built one. The layout is the pack itself.
    const keyed = fromOffer(
      {
        moves: [{ id: "push-on" }],
        trackers: [{ id: "marks", kind: "counter" }],
        setups: [{ id: "com.example.setups.starter", title: "Starter kit" }],
      },
      {
        moves: [{ id: "push-on" }, { id: "hold" }],
        counters: [{ id: "marks" }, { id: "scars" }],
        resources: [{ id: "stock" }],
      },
    );

    expect(keyed.moves.map((m) => m.id)).toEqual(["push-on", "hold"]);
    expect(keyed.counters.map((c) => c.id)).toEqual(["marks", "scars"]);
    expect(keyed.resources.map((r) => r.id)).toEqual(["stock"]);
    // The setups are the offer's either way: a layout carries none.
    expect(keyed.setups.map((s) => s.id)).toEqual(["com.example.setups.starter"]);
  });

  it("reads the offer alone where a page publishes no layout", () => {
    const offer = {
      moves: [{ id: "push-on" }],
      trackers: [
        { id: "marks", kind: "counter" as const },
        { id: "stock", kind: "resource" as const },
      ],
    };
    expect(fromOffer(offer)).toEqual(fromOffer(offer, null));
    expect(fromOffer(offer).moves.map((m) => m.id)).toEqual(["push-on"]);
    expect(fromOffer(offer).resources.map((r) => r.id)).toEqual(["stock"]);
  });

  it("gives a setup on both of the offer's lists one key, not two", () => {
    // `commands` on a run's offer is not the warps: it is every setup
    // again, offered the other way round. A profile has to pick one key
    // per setup, so the ones that read as warps become Command keys and
    // the rest Apply setup keys, and nothing is laid down twice.
    const both = [
      { id: "com.example.setups.starter", title: "Starter kit" },
      { id: "com.example.setups.summit", title: "Warp to the summit" },
    ];
    const keyed = fromOffer({ setups: both, commands: both });
    expect(keyed.setups.map((s) => s.id)).toEqual(["com.example.setups.starter"]);
    expect(keyed.commands.map((s) => s.id)).toEqual(["com.example.setups.summit"]);
  });

  it("builds the same bytes twice, so regenerating is not a diff", () => {
    for (const { spec } of all) {
      const twice = [container(profile(spec)), container(profile(spec))];
      expect([...twice[0]!], `${spec.slug}-${spec.device}`).toEqual([...twice[1]!]);
    }
  });

  it("rebuilds every profile committed under the plugin, byte for byte", () => {
    // A `.streamDeckProfile` is generated and committed rather than built
    // at install time, so a layout change nobody regenerated for leaves a
    // stale zip next to the source that no longer agrees with it.
    expect(all).toHaveLength(44);
    for (const { spec, built } of all) {
      const committed = readFileSync(path(`streamdeck/com.scrthq.runlog.sdPlugin/profiles/${spec.slug}-${spec.device}.streamDeckProfile`));
      expect(Buffer.from(container(built)).equals(committed), `${spec.slug}-${spec.device}`).toBe(true);
    }
  });
});
