import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { loadPackText, loadSetupText, type Pack, type Setup } from "@runlog/rules-schema";

import { PACK_PROFILES } from "../../../streamdeck/src/profiles.ts";
import { DEVICES, DEVICE_IDS } from "./layouts.ts";
import {
  container,
  fromOffer,
  fromPack,
  hasKeys,
  packKeys,
  paginate,
  profile,
  specs,
  specsFor,
  type Built,
  type StoredAction,
} from "./profiles.ts";

/**
 * The generator, held against the packs it reads and the grids its output
 * has to fit on.
 *
 * Nobody reads a `.streamDeckProfile`. It is a zip of compact JSON that
 * goes out with a release or off a pack's page and turns up on somebody's
 * desk, and the two ways it goes wrong, a key off the edge of a Mini and a
 * move whose id the pack renamed last month, both look to whoever imported
 * it like the plugin being broken. So the layout is held to the grid and to
 * the pack here, where a mistake costs a test run rather than a support
 * thread.
 *
 * The last and largest check is that this package rebuilds the forty-four
 * files committed under the plugin, byte for byte. Those are generated by
 * `streamdeck/design/profiles.mjs`, which is a Node script over this code;
 * proving the package alone reproduces them is what says a browser
 * building a profile for a Marketplace pack is building the same thing.
 */

const repo = new URL("../../../", import.meta.url);
const path = (rest: string) => fileURLToPath(new URL(rest, repo));

/** Every setup written for a tool, by title, the way the app's picker lists them. */
function setupsFor(tool: string | undefined): Setup[] {
  if (!tool) return [];
  const dir = path("packs/setups");
  const out: Setup[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".yaml"))) {
    const parsed = loadSetupText(readFileSync(`${dir}/${file}`, "utf8"), "yaml");
    if (parsed.ok && parsed.setup.tool.toLowerCase() === tool.toLowerCase()) out.push(parsed.setup);
  }
  return out.sort((a, b) => a.title.localeCompare(b.title));
}

/** The tool a pack is driven by, from the control profile written for it. */
function toolFor(packId: string): string | undefined {
  const dir = path("packs/profiles");
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const written = JSON.parse(readFileSync(`${dir}/${file}`, "utf8")) as { pack?: string; tool?: string };
    if (written.pack === packId) return written.tool;
  }
  return undefined;
}

/**
 * The layouts the plugin ships, read the way the generator reads them.
 *
 * The slug each pack ships under comes from `streamdeck/src/profiles.ts`,
 * the table the generator writes and the plugin switches through, rather
 * than from a second copy of the naming rule kept here.
 */
const shipped: Array<{ slug: string; pack: Pack | null; setups: Setup[] }> = [{ slug: "runlog", pack: null, setups: [] }];
for (const file of ["packs/demo/pack.yaml", ...readdirSync(path("packs/sketches")).map((f) => `packs/sketches/${f}`)]) {
  if (!file.endsWith(".yaml")) continue;
  const parsed = loadPackText(readFileSync(path(file), "utf8"), "yaml");
  if (!parsed.ok) continue;
  const slug = PACK_PROFILES[parsed.pack.id];
  if (slug) shipped.push({ slug, pack: parsed.pack, setups: setupsFor(toolFor(parsed.pack.id)) });
}

/** Every layout on every deck, built, with the slug it ships under. */
const all = shipped.flatMap(({ slug, pack, setups }) =>
  specs(pack, setups).map((spec) => ({ spec: { ...spec, slug }, built: profile({ ...spec, slug }) })),
);

/** Every action on every page of a built profile, with the page and position it sits at. */
function placed(built: Built): Array<{ page: string; controller: string; position: string; action: StoredAction }> {
  const out = [];
  for (const [page, file] of Object.entries(built.files)) {
    if (!("Controllers" in file)) continue;
    for (const controller of file.Controllers) {
      for (const [position, action] of Object.entries(controller.Actions ?? {})) {
        out.push({ page, controller: controller.Type, position, action });
      }
    }
  }
  return out;
}

describe("a deck laid out for a pack", () => {
  it("knows how big each deck is", () => {
    // Written out rather than taken from `DEVICES`, which is the table
    // under test: the grid check below reads the same numbers the layout
    // was built from, so without this it would pass on any pair of them.
    // These are the SDK's, from the `DeviceType` enumeration in
    // @elgato/schemas.
    expect(DEVICES.xl).toMatchObject({ type: 2, columns: 8, rows: 4, dials: 0 });
    expect(DEVICES.sd).toMatchObject({ type: 0, columns: 5, rows: 3, dials: 0 });
    expect(DEVICES.mini).toMatchObject({ type: 1, columns: 3, rows: 2, dials: 0 });
    expect(DEVICES.plus).toMatchObject({ type: 7, columns: 4, rows: 2, dials: 4 });
    expect(DEVICE_IDS).toEqual(Object.keys(DEVICES));
  });

  it("keeps a page's last slot for the way on, and its first for the way back", () => {
    const keys = Array.from({ length: 20 }, (_, i) => ({ action: `k${i}` }));
    // Six to a page: five on the first with the sixth spent going on, then
    // four with both turns, then the rest with only the way back.
    expect(paginate(keys, 6).map((p) => [p.back, p.more, p.keys.length])).toEqual([
      [false, true, 5],
      [true, true, 4],
      [true, true, 4],
      [true, true, 4],
      [true, false, 3],
    ]);
    // A layout that fits exactly grows no turn key pointing at nothing.
    expect(paginate(keys.slice(0, 6), 6)).toEqual([{ back: false, more: false, keys: keys.slice(0, 6) }]);
  });

  it("lays every key inside its own deck's grid", () => {
    for (const { spec, built } of all) {
      const { columns, rows, dials } = DEVICES[spec.device];
      for (const { controller, position } of placed(built)) {
        const [column, row] = position.split(",").map(Number);
        const width = controller === "Encoder" ? dials : columns;
        const height = controller === "Encoder" ? 1 : rows;
        expect(column, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(width);
        expect(row, `${spec.slug}-${spec.device} ${position}`).toBeLessThan(height);
        expect(column).toBeGreaterThanOrEqual(0);
        expect(row).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("puts one thing in one place", () => {
    for (const { spec, built } of all) {
      const seen = new Set<string>();
      for (const { page, controller, position } of placed(built)) {
        const where = `${page} ${controller} ${position}`;
        expect(seen.has(where), `${spec.slug}-${spec.device} doubles up on ${where}`).toBe(false);
        seen.add(where);
      }
    }
  });

  it("places nothing but our own actions and the app's page turns", () => {
    const manifest = JSON.parse(readFileSync(path("streamdeck/com.scrthq.runlog.sdPlugin/manifest.json"), "utf8")) as {
      Actions: Array<{ UUID: string }>;
    };
    const allowed = new Set([
      ...manifest.Actions.map((a) => a.UUID),
      "com.elgato.streamdeck.page.next",
      "com.elgato.streamdeck.page.previous",
    ]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        expect(allowed.has(action.UUID), `${spec.slug}-${spec.device} places ${action.UUID}`).toBe(true);
      }
    }
  });

  it("sets each key to what its own settings type allows", () => {
    // The shapes are `PressTarget`, `MetricField`, `SetupSettings` and
    // `NextSettings` in `streamdeck/src/state.ts`. A key set to something
    // the plugin cannot read draws "Set up" for ever and says nothing
    // about why.
    const fields = new Set(["score", "unit", "clock", "latest", "leader"]);
    const kinds = new Set(["roll", "move", "answer"]);
    for (const { spec, built } of all) {
      for (const { action } of placed(built)) {
        const settings = action.Settings;
        const where = `${spec.slug}-${spec.device} ${action.UUID}`;
        if (action.UUID === "com.scrthq.runlog.metric") {
          const field = settings["field"] as string | Record<string, string>;
          if (typeof field === "string") expect(fields.has(field), where).toBe(true);
          else
            expect(Object.keys(field), where).toSatisfy(
              (keys: string[]) => keys.length === 1 && ["counter", "resource"].includes(keys[0]!),
            );
        } else if (action.UUID === "com.scrthq.runlog.press") {
          const target = settings["target"] as { kind: string; id?: string };
          expect(kinds.has(target.kind), where).toBe(true);
          if (target.kind === "move") expect(typeof target.id, where).toBe("string");
        } else if (action.UUID === "com.scrthq.runlog.setup") {
          expect(Object.keys(settings["setup"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.command") {
          expect(Object.keys(settings["command"] as object).sort(), where).toEqual(["id", "title"]);
        } else if (action.UUID === "com.scrthq.runlog.open") {
          expect(["run", "guide", "rules", "newrun", "dock"], where).toContain(settings["target"]);
        } else {
          expect(settings, where).toEqual({});
        }
      }
    }
  });

  it("gives a + its dials, and no other deck one", () => {
    for (const { spec, built } of all) {
      const wheels = placed(built).filter((p) => p.controller === "Encoder");
      if (spec.device !== "plus") {
        expect(wheels, `${spec.slug}-${spec.device}`).toHaveLength(0);
        continue;
      }
      // Only Next, Metric and Clock declare `Encoder` in the manifest.
      for (const { action } of wheels) {
        expect(["com.scrthq.runlog.next", "com.scrthq.runlog.metric", "com.scrthq.runlog.clock"]).toContain(action.UUID);
      }
    }
  });

  it("gives every profile the run and the guide, and only a pack's the rules", () => {
    for (const { spec, built } of all) {
      const targets = placed(built)
        .filter((p) => p.action.UUID === "com.scrthq.runlog.open")
        .map((p) => (p.action.Settings as { target: string }).target)
        .sort();
      expect(targets, `${spec.slug}-${spec.device}`).toEqual(spec.slug === "runlog" ? ["guide", "run"] : ["guide", "rules", "run"]);
    }
  });

  it("carries exactly the pack's moves, its shown counters, its resources and its tool's setups", () => {
    // A key set to a move the pack renamed last month is dead on somebody's
    // deck and says nothing about why, so what is placed is held against
    // the pack itself rather than counted.
    for (const { slug, pack, setups } of shipped) {
      if (!pack) continue;
      for (const { spec, built } of all.filter((b) => b.spec.slug === slug)) {
        const settings = placed(built).map((p) => p.action.Settings);
        const where = `${spec.slug}-${spec.device}`;

        const moves = settings.filter((s) => (s["target"] as { kind?: string } | undefined)?.kind === "move");
        expect(moves.map((s) => (s["target"] as { id: string }).id).sort(), where).toEqual(Object.keys(pack.moves ?? {}).sort());

        const numbers = (which: "counter" | "resource") =>
          settings
            .filter((s) => typeof s["field"] === "object" && which in (s["field"] as object))
            .map((s) => (s["field"] as Record<string, string>)[which]!);
        const shownCounters = Object.entries(pack.counters ?? {})
          .filter(([, c]) => !c.hidden)
          .map(([id]) => id);
        expect(numbers("counter").sort(), where).toEqual(shownCounters.sort());
        expect(numbers("resource").sort(), where).toEqual(Object.keys(pack.resources ?? {}).sort());

        const handedOut = settings
          .filter((s) => s["setup"] ?? s["command"])
          .map((s) => ((s["setup"] ?? s["command"]) as { id: string }).id);
        expect(handedOut.sort(), where).toEqual(setups.map((s) => s.id).sort());
      }
    }
  });

  it("gives the demo pack no setup keys, because it names no tool", () => {
    const built = all.find(({ spec }) => spec.slug === "demo" && spec.device === "xl")!.built;
    expect(placed(built).filter((p) => p.action.UUID === "com.scrthq.runlog.setup")).toHaveLength(0);
  });

  it("offers a deck only to a pack with something of its own to put on one", () => {
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(hasKeys(demo)).toBe(true);
    expect(hasKeys({ ...demo, moves: undefined, counters: undefined, resources: undefined })).toBe(false);
    expect(hasKeys({ ...demo, counters: undefined, resources: undefined })).toBe(true);
  });

  it("names a profile after the pack, and a Marketplace one after its id", () => {
    // The shipped forty-four are written under the short slug their file
    // is named by, which the generator puts on each spec; a pack from the
    // Marketplace has no such file, so its id is what names the download.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    expect(specs(demo, [], "xl")).toEqual([{ slug: demo.id, device: "xl", name: demo.title, keys: expect.anything() }]);
    expect(specs(null, []).map((s) => `${s.slug}-${s.device}`)).toEqual(["runlog-xl", "runlog-sd", "runlog-mini", "runlog-plus"]);
  });

  it("lays a run's own offer out the way it lays the pack file out", () => {
    // The plugin follows runs, not packs. A pack from the Marketplace is
    // not on the deck's disk and never will be, so a profile for it is
    // built from what the run publishes about itself: the moves, the
    // trackers, and the setups for the tool. The two adapters are held
    // against each other here, because the day they disagree is the day a
    // key built from a run presses something the shipped profile does not.
    const demo = shipped.find((l) => l.slug === "demo")!.pack!;
    const setup = (id: string, title: string): Setup => ({
      kind: "setup",
      schemaVersion: 1,
      id: `com.example.setups.${id}`,
      version: "1.0.0",
      title,
      tool: "ExampleTool",
      ops: [{ op: "flag.set", args: { name: id } }],
    });
    // One of each, because which key a setup takes is the one thing the
    // two adapters have to agree about: a warp goes to a Command key and
    // everything else to an Apply setup key.
    const setups = [setup("starter", "Starter kit"), setup("summit", "Warp to the summit")];

    // The offer as the page publishes it: every setup in `setups`, and the
    // same list again in `commands` less whatever the wire would drop,
    // which is nothing here. A hidden counter is published by neither.
    const shown = Object.entries(demo.counters ?? {}).filter(([, c]) => !c.hidden);
    const offer = {
      moves: Object.keys(demo.moves ?? {}).map((id) => ({ id, label: id })),
      trackers: [
        ...shown.map(([id]) => ({ id, kind: "counter" as const, label: id })),
        ...Object.keys(demo.resources ?? {}).map((id) => ({ id, kind: "resource" as const, label: id })),
      ],
      setups: setups.map(({ id, title }) => ({ id, title })),
      commands: setups.map(({ id, title }) => ({ id, title })),
    };

    expect(packKeys(fromOffer(offer))).toEqual(packKeys(fromPack(demo, setups)));
    // And the same profile, byte for byte, under the same name and slug.
    const named = { slug: demo.id, name: demo.title };
    expect([...container(profile(specsFor(fromOffer(offer), named, "xl")[0]!))]).toEqual([
      ...container(profile(specs(demo, setups, "xl")[0]!)),
    ]);
  });

  it("gives a setup on both of the offer's lists one key, not two", () => {
    // `commands` on a run's offer is not the warps: it is every setup
    // again, offered the other way round. A profile has to pick one key
    // per setup, so the ones that read as warps become Command keys and
    // the rest Apply setup keys, and nothing is laid down twice.
    const both = [
      { id: "com.example.setups.starter", title: "Starter kit" },
      { id: "com.example.setups.summit", title: "Warp to the summit" },
    ];
    const keyed = fromOffer({ setups: both, commands: both });
    expect(keyed.setups.map((s) => s.id)).toEqual(["com.example.setups.starter"]);
    expect(keyed.commands.map((s) => s.id)).toEqual(["com.example.setups.summit"]);
  });

  it("builds the same bytes twice, so regenerating is not a diff", () => {
    for (const { spec } of all) {
      const twice = [container(profile(spec)), container(profile(spec))];
      expect([...twice[0]!], `${spec.slug}-${spec.device}`).toEqual([...twice[1]!]);
    }
  });

  it("rebuilds every profile committed under the plugin, byte for byte", () => {
    // A `.streamDeckProfile` is generated and committed rather than built
    // at install time, so a layout change nobody regenerated for leaves a
    // stale zip next to the source that no longer agrees with it.
    expect(all).toHaveLength(44);
    for (const { spec, built } of all) {
      const committed = readFileSync(path(`streamdeck/com.scrthq.runlog.sdPlugin/profiles/${spec.slug}-${spec.device}.streamDeckProfile`));
      expect(Buffer.from(container(built)).equals(committed), `${spec.slug}-${spec.device}`).toBe(true);
    }
  });
});
