"""The names TarnishedTool knows, so the Control panel can offer them.

Run by hand against a checkout of the fork, because the fork is a
separate repository and this is not a thing that changes between
releases of the game:

    python scripts/extract-tool-lists.py ../TarnishedTool-runlog-integration

The panel asks somebody to name a grace, an item or a weapon, and
before this it asked with an empty box: the names are exact, the game
has four hundred of each, and there was nowhere to look them up
without leaving the run. The lists come from the tool's own resources,
which is the same data it will match the name against when the frame
arrives, so a name the panel offers is a name the tool accepts.

MIT, from borgCode/TarnishedTool by Shilkey. The names themselves are
Elden Ring's.
"""
import json, sys, os
import csv
import io
import xml.etree.ElementTree as ET

root = sys.argv[1] if len(sys.argv) > 1 else "../TarnishedTool-runlog-integration"
resx = os.path.join(root, "TarnishedTool", "Properties", "Resources.resx")
out = os.path.join(os.path.dirname(__file__), "..", "apps", "web", "src", "control", "lists", "tarnishedtool.json")

data = {d.get("name"): (d.findtext("value") or "") for d in ET.parse(resx).getroot().findall("data")}
# A proper CSV read, not a split on every comma. Several names carry one:
# "Burn, O Flame!" and "Flame, Grant me Strength" among them. Splitting
# blindly cut those in half and shifted every column after them, so the
# name in column three came out as a fragment: the list offered `"Burn`
# and `"Flame`, and the incantations themselves were missing from it
# entirely. A name missing from this list is a rule the panel cannot
# offer and a setup that cannot be written, which is the exact failure
# the list exists to prevent.
rows = lambda key: [r for r in csv.reader(io.StringIO(data[key])) if r and any(c.strip() for c in r)]

# Graces: dlc flag, area, name, and two numbers the tool resolves itself.
graces = sorted({(r[2].strip(), r[1].strip()) for r in rows("Graces") if len(r) >= 3})

# Everything `item.named` will match against, in the same order the tool
# builds its own pool. Key items only where the tool hands them over
# without an event behind them: the rest are tied to an event flag, and
# handing one over without the event is how a quest breaks.
#
# Which ones those are is column five, the tool's own `NeedsEvent`, and
# not column six. This read column six -- "has an event id" -- which is
# nearly the same set and not the same set: it left out eight key items
# the tool gives quite happily, and offered `Rold Medallion`, which the
# tool refuses. A name this list offers that the tool refuses is the
# exact failure the list exists to prevent, so it reads the flag the
# tool reads.
ITEMS = ["Consumables", "UpgradeMaterials", "CraftingMaterials", "CrystalTears", "Talismans", "Armor", "Arrows", "PotsAndPerfumes", "Sorceries", "Incantations"]
items = {r[2].strip() for key in ITEMS for r in rows(key) if len(r) >= 3}
items |= {r[2].strip() for r in rows("KeyItems") if len(r) >= 6 and r[5].strip() != "1"}

# Weapons carry how far they reinforce: the ordinary ones to +25, the
# ones on somber stones to +10. The panel holds the level to that.
weapons = sorted({(r[1].strip(), 10 if r[4].strip() == "1" else 25) for r in rows("Weapons") if len(r) >= 5})

# Ashes of war, which is the one id left on an operation that has a
# name for it sitting right here.
ashes = sorted({r[1].strip() for r in rows("AoW") if len(r) >= 2})

# Every boss the tool can put somebody in front of. The coordinates are
# the tool's business and stay there: what comes over the wire is the
# name, and the region beside it because forty of these are the same
# fight in two places.
bosses = sorted({(r[2].strip(), r[1].strip()) for r in rows("BossWarps") if len(r) >= 3})

payload = {
    "tool": "TarnishedTool",
    "note": "Generated by scripts/extract-tool-lists.py from the tool's own resources (MIT, borgCode/TarnishedTool). Do not edit by hand.",
    "graces": [{"name": n, "area": a} for n, a in graces],
    "items": sorted(items),
    "weapons": [{"name": n, "max": m} for n, m in weapons],
    "ashes": [{"name": n} for n in ashes],
    "bosses": [{"name": n, "area": a} for n, a in bosses],
}
with open(out, "w", encoding="utf-8", newline="\n") as f:
    json.dump(payload, f, ensure_ascii=False, indent=1)
    f.write("\n")
print(", ".join(f"{len(payload[k])} {k}" for k in ("graces", "items", "weapons", "ashes", "bosses")), "->", os.path.relpath(out))
